fix (357,12): Error CS0136: A local variable named 'i' cannot be declared in this scope because it would give a different meaning ti 'i', wich is already used in a p'parent or current' scope to denote somtehing else